id: monitor_dependabot_activity
learningObjectives:
  - Monitor and review Dependabot pull requests.
hints:
  - Check the 'Pull requests' tab in your GitHub repository for new Dependabot
    suggestions.
  - Review the code changes in each pull request to ensure they meet your
    standards.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: lucca
        messages:
          - text: Alright, the setup is done, but the journey doesn't end here.
          - text: Now, it's time to watch for Dependabot-generated pull requests. Keep an
              eye on the [Actions Tab](${user.repository}/actions/workflows/dependabot/dependabot-updates) and check its progress.
          - text: While the Dependabot action is running (might take a few minutes to complete) it will create a bunch of pull requests as it goes.
          - text: Keep an eye on [your Pull Requests tab](${user.repository}/pulls) as dependabot creates them.
          - text: Choose one of the Dependabot pull requests from the list and copy the branch name.
          - text: ":instruction[Give me the PR **branch name** so i'll merge it]."

trigger:
  type: user_message
  flowNode:
    do:
      - actionId: github_repo_api
        name: get_branch_name
        params:
          method: get
          path: /branches/${userMessageText}
    if:
      conditions:
        - conditionId: text_contains_strings
          params:
            text: "${userMessageText}"
            strings:
              - dependabot/
        - conditionId: is_truthy
          params:
            value: ${outputs.get_branch_name.data?.name}
      then:
        do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: Thanks for the update! I'll merge the PR for you. Give me a moment.
          - actionId: github_merge_pr
            params:
              headBranch: ${userMessageText}
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: "🚀 Automate with Dependabot"
                - text: "You've just completed the Automate with Dependabot quest—great job! This experience helped you configure GitHub Dependabot to automatically scan your project’s dependencies for vulnerabilities, set up update configurations, and review automated pull requests to keep your codebase secure and up to date."
                - text: "🧠 What's Next?"
                - text: "To strengthen your skills and validate your expertise, pursue the official:"
                - text: "👉 [GitHub Advanced Security Certification](https://learn.microsoft.com/en-us/credentials/certifications/github-advanced-security/)"
                - text: "Earn a verified credential from GitHub that demonstrates your ability to implement secure development workflows, including dependency and vulnerability management with Dependabot. This certification page provides direct access to the required learning paths, skills modules, and the certification exam."
          - actionId: finish_step

      else:
        do:
          - actionId: bot_message
            params:
              person: lucca
              messages:
                - text: Are you sure? It doesn't seem like a Dependabot branch. Please try again.
